/**********************************************************************************************************************
 * FlsLoader exclusive area (integration) — required by FlsLoader.c
 * Demo reference: MC-ISAR .../McalDemo/.../Integration/FlsLdr_ExclArea.*
 * Not generated by DaVinci/tresos; keep under Appl.
 *********************************************************************************************************************/
#ifndef FLSLDR_EXCLAREA_H
#define FLSLDR_EXCLAREA_H

extern void FlsLdr_ExclArea_PfProg_Enter(void);
extern void FlsLdr_ExclArea_PfProg_Exit(void);
extern void FlsLdr_ExclArea_PfErase_Enter(void);
extern void FlsLdr_ExclArea_PfErase_Exit(void);

/* Call after FlsLoader_Erase / FlsLoader_Write returns (Exit is empty while busy). */
extern void FlsLdr_ExclArea_PfBusy_Release(void);

#endif /* FLSLDR_EXCLAREA_H */
